### PR TITLE
Change brand to fcp for Show Report template

### PR DESCRIPTION
**Pull request by jwade1327**
Screen Shot 2022-01-06 at 9 00 25 AM

### CODE REVIEW

**Comment by jwade1327** [comment]
Show Report NL=no brand
Screen Shot 2022-01-06 at 9 55 34 AM
All other newsletters =brand is shown
Screen Shot 2022-01-06 at 9 59 14 AM

**Comment by jwade1327** [comment]
[eNL Template, Show report](https://trello.com/c/lURJkulj/142-enl-template-show-report)

**Review by Shinsina — APPROVED** [review]

**Comment by Shinsina** [comment]
@jwade1327 Actually can you make ```brand`` something like ```showBrand```? Calling it just brand doesn't really indicate what it's doing.

**Comment by jwade1327** [comment]
@Shinsina Updated!

**Review by Shinsina — APPROVED** [review]

**Pull request merged**
